---

- name: "Provision {{ vm.name }}" 
  block:
    - name: "Create image for {{ vm.name }}"
      command: "qemu-img create -b {{ vm.base_image }} -f qcow2 {{ image_path }}"

    - name: "Define {{ vm.name }}"
      virt:
        name: "{{ vm.name }}"
        command: define 
        xml: "{{ lookup('template', 'vm_template.xml.j2')}}"

    - name: "Add group metadata"
      command: "virsh metadata {{ vm.name }} --uri qemu:///system --key group --set '<group>{{ vm.group | default(none)}}</group>' --config"
  become: true
