---

- name: Gather libvirt environment state information
  set_fact: 
    kvm_env_state: "{{ libvirt.connection | get_libvirt_env_state }}"
  become: true

- name: Gather desired vm names
  set_fact:
    vm_names: "{{ vm_names | default([]) + [vm.name] }}"
  with_items:
    - "{{ libvirt.vms }}"
  loop_control:
    loop_var: vm