---

- name: Ensure vms exist
  block:
    - name: "Gather facts"
      set_fact:
        template_path: "{{ kvm_config.storage_pool }}/{{ kvm_config.base_template }}"
        base_image_path: "{{ kvm_config.storage_pool }}/{{ kvm_config.base_image }}"
        created_image_path: "{{ kvm_config.storage_pool }}/{{ vm.name }}.qcow2"

    - name: "Create image for {{ vm.name }}"
      command: "qemu-img create -b {{ base_image_path }} -f qcow2 {{ created_image_path }}"

    - name: "Provision vm from template"
      command: "virt-clone --original-xml={{ template_path }} -f {{ created_image_path }} -n {{ vm.name }} --preserve-data"
  when:
  - vm.name not in kvm_env_state.keys()
  become: yes