---

- name: "Destroy {{ existing_vm.key }}"
  command: "virsh destroy {{ existing_vm.key }}"
  become: true
  when: 
    - existing_vm.value.state == 1

- name: "Undefine {{ existing_vm.key }}"
  command: "virsh undefine {{ existing_vm.key }}"
  become: true

- name: "set {{ existing_vm.key }} qcow2 file name"
  set_fact:
    qcow2_file_name: "{{ existing_vm.key }}.qcow2"

- name: "remove {{ existing_vm.key }}.qcow2 when in storage_pool"
  file:
    path: "{{ kvm_config.storage_pool }}/{{existing_vm.key }}.qcow2"
    state: absent
  become: true
  when:
    - qcow2_file_name in existing_qcow2_files.stdout